export const GET_PAYMENT_LIST_REQUEST = 'GET_PAYMENT_LIST_REQUEST';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';
export const GET_PAYMENT_FAIL = 'GET_PAYMENT_FAIL';

export const GET_PAYMENT_DETAIL_REQUEST = 'GET_PAYMENT_DETAIL_REQUEST';
export const GET_PAYMENT_DETAIL_SUCCESS = 'GET_PAYMENT_DETAIL_SUCCESS';
export const GET_PAYMENT_DETAIL_FAIL = 'GET_PAYMENT_DETAIL_FAIL';

export const POST_PAYMENT_FOR_MAKER_REQUEST = 'POST_PAYMENT_FOR_MAKER_REQUEST';
export const POST_PAYMENT_FOR_CHECKER_REQUEST = 'POST_PAYMENT_FOR_CHECKER_REQUEST';
export const SAVE_PAYMENT_SUCCESS = 'SAVE_PAYMENT_SUCCESS';
export const SAVE_PAYMENT_FAIL = 'SAVE_PAYMENT_FAIL';

export const GET_AUDIT_TRAIL_REQUEST = 'GET_AUDIT_TRAIL_REQUEST';
export const GET_AUDIT_TRAIL_SUCCESS = 'GET_AUDIT_TRAIL_SUCCESS';
export const GET_AUDIT_TRAIL_FAIL = 'GET_AUDIT_TRAIL_FAIL';

export const GET_PRESIGNED_DOCUMENT_REQUEST = 'GET_PRESIGNED_DOCUMENT_REQUEST';
export const GET_PAYMENT_LIST_FOR_ROLE_REQUEST = 'GET_PAYMENT_LIST_FOR_ROLE_REQUEST';
export const UPDATE_CLEAR_OS_FAIL = 'UPDATE_CLEAR_OS_FAIL';
