// post delegation for user
export const POST_DELEGATION_TO_USER_REQUEST = 'POST_DELEGATION_TO_USER_REQUEST';
export const POST_DELEGATION_TO_USER_SUCCESS = 'POST_DELEGATION_TO_USER_SUCCESS';
export const POST_DELEGATION_TO_USER_FAIL = 'POST_DELEGATION_TO_USER_FAIL';

// validation and delegation for user
export const POST_ACTIVE_DELEGATION_REQUEST = 'POST_ACTIVE_DELEGATION_REQUEST';
export const POST_ACTIVE_DELEGATION_SUCCESS = 'POST_ACTIVE_DELEGATION_SUCCESS';
export const POST_ACTIVE_DELEGATION_FAIL = 'POST_ACTIVE_DELEGATION_FAIL';

// show Delegation
export const GET_DELEGATION_USER_REQUEST = 'GET_DELEGATION_USER_REQUEST';
export const GET_DELEGATION_USER_SUCCESS = 'GET_DELEGATION_USER_SUCCESS';
export const GET_DELEGATION_USER_FAIL = 'GET_DELEGATION_USER_FAIL';

export const SHOW_DELEGATION_USER_FIXED = 'SHOW_DELEGATION_USER_FIXED';
export const HIDE_DELEGATION_USER_FIXED = 'HIDE_DELEGATION_USER_FIXED';
export const GET_LIST_USER = 'GET_LIST_USER';

export const GET_LIST_MY_DELEGATED_REQUEST = 'GET_LIST_MY_DELEGATED_REQUEST';
export const GET_MY_DELEGATED_SUCCESS = 'GET_MY_DELEGATED_SUCCESS';
export const GET_MY_DELEGATED_FAIL = 'GET_MY_DELEGATED_FAIL';

export const GET_DELEGATE_TO_REQUEST = 'GET_DELEGATE_TO_REQUEST';
export const GET_DELEGATE_TO_SUCCESS = 'GET_DELEGATE_TO_SUCCESS';
export const GET_DELEGATE_TO_FAIL = 'GET_DELEGATE_TO_FAIL';

export const POST_CANCEL_DELEGATION_USER_REQUEST = 'POST_CANCEL_DELEGATION_USER_REQUEST';
export const POST_CONFIRM_DELEGATE_TO_REQUEST = 'POST_CONFIRM_DELEGATE_TO_REQUEST';
export const GET_LIST_USER_FROM_ROLES_REQUEST = 'GET_LIST_USER_FROM_ROLES_REQUEST';
